### ISSUE TITLE
Label for empty folders ?

### ISSUE THREAD

**Issue by jcolomb** [tonic-team/Tonic-Research-Project-Template#6]
I have been using the template for a couple of project and it is quite difficult to find things in the beginning due to the large amount of empty folders.

I got an idea yesterday: what about labelling empty folders by starting their name with "empty". The template would then  have all folders labeled, and users will be asked to erase the label when putting something on that folder.

I have not tried it on my repo yet, but will let you know.

**Comment by jcolomb** [comment]
implemented in #10, waiting for review/testing

**Comment by deeptimittal12** [comment]
It is a good option to label but is it possible to have a script/command for displaying empty folders and subfolders in a repo?

**Comment by jcolomb** [comment]
Not merged, too dangerous as some folder should never be renamed
